name: 🆘 Support & Setup Help
description: Get help with Unraid Connect Integration setup, configuration, or troubleshooting
title: "[Support] "
labels: ["question", "help wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 🆘 Support & Setup Help

        Need help with the Unraid Connect Integration? This template is for **setup assistance, configuration questions, and general troubleshooting**.

        ## ⚠️ Beta Software Notice
        This integration is currently in **beta phase** (v0.1.0-beta.6) due to the evolving Unraid GraphQL API. For production use, consider the [SSH-based integration](https://github.com/domalab/ha-unraid).

        ## 📋 When to use this template:
        - ✅ You need help setting up the integration for the first time
        - ✅ You're having trouble connecting to your Unraid server via GraphQL API
        - ✅ You need clarification on configuration options
        - ✅ You want to understand how certain features work
        - ✅ You've followed troubleshooting guides but still need help

        ## ❌ When NOT to use this template:
        - 🚫 **Bug reports**: Something was working but now it's broken → Use "Bug Report" template
        - 🚫 **Feature requests**: Want new functionality → Use "Feature Request" template
        - 🚫 **Known limitations**: Issues documented in [GitHub Issues #1-#13](https://github.com/domalab/ha-unraid-connect/issues)

        ## 📚 Before You Continue

        Please check these resources first:
        - 📖 [Documentation](https://github.com/domalab/ha-unraid-connect/blob/main/README.md) - Comprehensive setup and usage guide
        - 📖 [Setup Guide](https://github.com/domalab/ha-unraid-connect/blob/main/docs/setup.md) - Step-by-step setup instructions
        - 🔍 [Known Limitations](https://github.com/domalab/ha-unraid-connect/issues) - Current API limitations and issues
        - 💬 [Community Forum](https://community.home-assistant.io/) - Community discussions and help

  - type: dropdown
    id: support_category
    attributes:
      label: 🏷️ Support Category
      description: "What type of help do you need?"
      options:
        - "Initial setup and configuration"
        - "Connection issues (can't connect to Unraid)"
        - "Authentication problems (API key/GraphQL)"
        - "Unraid Connect plugin setup"
        - "Missing entities or sensors"
        - "Understanding integration features and limitations"
        - "Performance or reliability issues"
        - "Configuration options questions"
        - "GraphQL API endpoint issues"
        - "General usage questions"
        - "Other"
    validations:
      required: true

  - type: input
    id: unraid_version
    attributes:
      label: 🖥️ Unraid Version
      description: "Your Unraid server version"
      placeholder: "6.12.6"
    validations:
      required: true

  - type: input
    id: ha_version
    attributes:
      label: 🏠 Home Assistant Version
      description: "Your Home Assistant version (2025.1.0+ required)"
      placeholder: "2025.6.0"
    validations:
      required: true

  - type: input
    id: unraid_connect_plugin_version
    attributes:
      label: 🔌 Unraid Connect Plugin Version
      description: "Version of the Unraid Connect plugin (check in Unraid plugins)"
      placeholder: "2025.05.01.2159"
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: 📦 Integration Version
      description: "Version of the Unraid Connect Integration (check in HACS or manifest.json)"
      placeholder: "v0.1.0-beta.6"
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: 📝 Problem Description
      description: "Describe the issue you're experiencing or what you need help with"
      placeholder: |
        **What are you trying to do:**
        I'm trying to set up the Unraid Connect integration but getting connection errors.

        **What's happening:**
        When I try to configure the integration, I get "Failed to connect" error.

        **What you've tried:**
        - Checked IP address and API key
        - Verified Unraid Connect plugin is enabled
        - Checked GraphQL endpoint accessibility
        - Restarted Home Assistant
      render: markdown
    validations:
      required: true

  - type: textarea
    id: network_setup
    attributes:
      label: 🌐 Network Setup
      description: "Information about your network configuration"
      placeholder: |
        - Unraid server IP: 192.168.1.100
        - Home Assistant IP: 192.168.1.50
        - Same subnet: Yes/No
        - VLANs or firewalls: None/Details
        - Unraid Connect plugin port: Default/Custom
        - Can you access GraphQL endpoint: Yes/No/Unknown
        - GraphQL URL accessible: http://unraid-ip/graphql
      render: markdown
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: ⚠️ Error Messages
      description: "Any error messages from Home Assistant logs or during setup"
      placeholder: |
        **Setup errors:**
        "Failed to connect to Unraid server"

        **Home Assistant logs:**
        ```
        2025-06-11 10:30:00 ERROR (MainThread) [custom_components.unraid_connect] ...
        ```

        **GraphQL endpoint test:**
        Can you access http://unraid-ip/graphql in browser: Yes/No

        **API key test:**
        Have you verified the API key is correct: Yes/No
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: troubleshooting_steps
    attributes:
      label: 🔧 Troubleshooting Steps Completed
      description: "Please confirm what you've already tried"
      options:
        - label: "I have read the [documentation](https://github.com/domalab/ha-unraid-connect/blob/main/README.md)"
          required: true
        - label: "I have checked the [setup guide](https://github.com/domalab/ha-unraid-connect/blob/main/docs/setup.md)"
          required: true
        - label: "I have reviewed [known limitations](https://github.com/domalab/ha-unraid-connect/issues)"
          required: true
        - label: "I have verified the Unraid Connect plugin is enabled"
          required: false
        - label: "I have confirmed my API key is correct"
          required: false
        - label: "I have tried restarting Home Assistant"
          required: false
        - label: "I understand this is beta software with limitations"
          required: true

  - type: textarea
    id: configuration_details
    attributes:
      label: ⚙️ Configuration Details
      description: "Details about your current configuration attempt"
      placeholder: |
        **Integration configuration:**
        - Host/IP: 192.168.1.100
        - API Key: [First few characters only]
        - Verify SSL: Yes/No
        - Update intervals: Default

        **Unraid Connect plugin settings:**
        - Plugin enabled: Yes/No
        - Developer Sandbox enabled: Yes/No
        - GraphQL endpoint accessible: Yes/No
        - Plugin version: 2025.05.01.2159
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: 📝 Additional Information
      description: "Any other relevant information about your setup"
      placeholder: |
        - Home Assistant installation type (HAOS, Docker, etc.)
        - Network setup details (VLANs, firewalls, etc.)
        - Previous attempts or workarounds tried
        - Specific entities or features you're having trouble with
        - Screenshots of error messages (if applicable)
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: help_preference
    attributes:
      label: 🤝 How Can We Help?
      description: "What type of assistance would be most helpful?"
      options:
        - label: "I need step-by-step setup guidance"
        - label: "I need help troubleshooting a specific error"
        - label: "I need clarification on how features work"
        - label: "I'm willing to provide additional debugging information"
        - label: "I'm available for real-time troubleshooting if needed"

  - type: markdown
    attributes:
      value: |
        ## 📚 Helpful Resources

        - **📖 Documentation**: [Unraid Connect Integration Docs](https://github.com/domalab/ha-unraid-connect/blob/main/README.md)
        - **📖 Setup Guide**: [Step-by-step Setup](https://github.com/domalab/ha-unraid-connect/blob/main/docs/setup.md)
        - **🔍 Known Issues**: [Current Limitations](https://github.com/domalab/ha-unraid-connect/issues)
        - **💬 Community**: [Home Assistant Community Forum](https://community.home-assistant.io/)
        - **🔄 SSH Alternative**: [Production-ready SSH Integration](https://github.com/domalab/ha-unraid)

        ## ⏱️ What Happens Next?

        1. **Review**: We'll review your setup and issue details
        2. **Guidance**: We'll provide specific troubleshooting steps or configuration help
        3. **Follow-up**: We may ask for additional information or logs
        4. **Resolution**: We'll work with you to resolve the issue
        5. **Documentation**: If needed, we'll update docs to help others with similar issues

        **Note**: For complex setup issues, we may suggest using the [Community Forum](https://community.home-assistant.io/) where more users can help. For production use, consider the [SSH-based integration](https://github.com/domalab/ha-unraid).

        Thank you for using the Unraid Connect Integration! 🙏
